[webservers]
# Real production hosts in Private Subnets (accessed via Bastion Jump Host or AWS SSM)
web-node-01 ansible_host=10.0.10.15 ansible_user=ubuntu
web-node-02 ansible_host=10.0.20.45 ansible_user=ubuntu

[bastion]
bastion-01 ansible_host=54.210.12.89 ansible_user=ubuntu

[webservers:vars]
ansible_ssh_common_args='-o ProxyJump=ubuntu@54.210.12.89'
app_env=production
app_root=/var/www/task-tutor
php_version=8.2
